feature:
  - changed-files:
      - any-glob-to-any-file: "**/*.kt"

dependencies:
  - changed-files:
      - any-glob-to-any-file: "gradle/**"

ci-cd:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
