feature:
  - changed-files:
      - any-glob-to-any-file: '*'
  - changed-files:
      - not-all-globs-to-all-files: ['gradle/**', '.github/**']

dependencies:
  - changed-files:
      - any-glob-to-any-file: 'gradle/**'

ci-cd:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
