changelog:
  categories:
    - title: 🎉 Features
      labels:
        - 'feature'
    - title: 🛠 Dependencies
      labels:
        - 'dependencies'
    - title: 🔄 CI/CD
      labels:
        - 'ci-cd'
