[plugins]
springBoot = { id = "org.springframework.boot", version = "3.4.5" }
springDependencyManagement = { id = "io.spring.dependency-management", version = "1.1.7" }

[libraries]
springBootStarter = { group = "org.springframework.boot", name = "spring-boot-starter" }
springBootStarterWeb = { group = "org.springframework.boot", name = "spring-boot-starter-web" }