name: labeler

on:
  pull_request_target: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: label
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v5
