name: lint

on:
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: setup java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: zulu
          java-version: 21

      - name: setup gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4

      - name: gradle lint
        run: ./gradlew lint
