name: main (monolith)

on:
  push:
    branches:
      - "main"

permissions:
  checks: write
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: setup java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v4
        with:
          distribution: zulu
          java-version: 21

      - name: setup gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: gradle test
        run: ./gradlew test

      - name: gradle assemble
        run: ./gradlew assemble

      - name: publish junit report
        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5
        if: always()
        with:
          report_paths: "**/test-junit-xml/**/TEST-*.xml"
          simplified_summary: true

  generate-tag:
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: generate tag
        id: tag
        run: |
          export TZ="Europe/Stockholm"
          timestamp=$(date +'%y%m%d-%H%M%S')
          echo "tag=$timestamp" >> $GITHUB_OUTPUT

  build-push:
    runs-on: ubuntu-latest
    needs: [generate-tag]
    strategy:
      matrix:
        image:
          - name: monolith
            dockerfile: services/monolith/Dockerfile
            gradle-task: "assemble"
          - name: monolith-native
            dockerfile: services/monolith/Dockerfile.graal
            gradle-task: ":monolith:nativeCompile -Pnative --no-configuration-cache"
            tag-suffix: "-native"
    steps:
      - name: checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: setup java
        uses: graalvm/setup-graalvm@7a1da54cb7fdef4ea19f6ecdfa9ecf59dc5a48fe # v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: install musl
        shell: bash
        run: sudo apt-get install -y musl musl-tools zlib1g-dev

      - name: gradle ${{ matrix.image.name }}
        run: ./gradlew ${{ matrix.image.gradle-task }}

      - name: build and push docker image
        uses: ./.github/actions/docker-build-push
        with:
         dockerfile: ${{ matrix.image.dockerfile }}
         github-token: ${{ secrets.GITHUB_TOKEN }}
         tag: ${{ needs.generate-tag.outputs.tag }}${{ matrix.image.tag-suffix }}

  publish-tag:
    runs-on: ubuntu-latest
    needs: [generate-tag, build-push]
    steps:
      - name: checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: publish tag
        run: |
          git tag ${{ needs.generate-tag.outputs.tag }}
          git push origin ${{ needs.generate-tag.outputs.tag }}

  release-to-development:
    runs-on: ubuntu-latest
    environment: development
    needs: [generate-tag, publish-tag]
    steps:
      - name: releasing to development
        run: echo "releasing tag ${{ needs.generate-tag.outputs.tag }} to development"

  release-to-staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: [generate-tag, release-to-development]
    steps:
      - name: releasing to staging
        run: echo "releasing tag ${{ needs.generate-tag.outputs.tag }} to staging"
