name: pull request

on:
  pull_request:
    branches:
      - "main"

permissions:
  checks: write
  pull-requests: write

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: setup java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v4
        with:
          distribution: zulu
          java-version: 21

      - name: setup gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: test
        run: ./gradlew test

      - name: gradle assemble
        run: ./gradlew assemble

      - name: publish junit report
        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5
        if: always()
        with:
          report_paths: '**/test-junit-xml/**/TEST-*.xml'
          simplified_summary: true
