name: pull request

on:
  pull_request:
    branches:
      - 'main'

permissions:
  checks: write
  pull-requests: write

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: setup java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: zulu
          java-version: 21

      - name: setup gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4

      - name: gradle test
        run: ./gradlew test

      - name: gradle build
        run: ./gradlew build

      - name: publish junit report
        uses: mikepenz/action-junit-report@cf701569b05ccdd861a76b8607a66d76f6fd4857 # v5
        if: always()
        with:
          report_paths: '**/test-junit-xml/**/TEST-*.xml'
          simplified_summary: true
