name: release to development

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  release-to-development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: releasing to production
        run: echo "releasing tag ${{ github.ref_name }} to development"
